from pymongo import MongoClient


# Do not edit this file

# Connect to MongoDB Atlas
connection_string = "mongodb+srv://alejandrovelez:YVES27@cluster0.snymu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a client and connect to database
client = MongoClient(connection_string)

# Access NOSTYLIST db
db = client["NOSTYLIST"]
