from pymongo import MongoClient


# Do not edit this file

# Make all database metadata immutable outside this file
class MongoDB:
    def __init__(self):
        # Connect to MongoDB Atlas
        self.__connection_string = "mongodb+srv://alejandrovelez:YVES27@cluster0.snymu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

        # Create a client and connect to database
        self.__client = MongoClient(self.__connection_string)

        # Access NOSTYLIST db
        self.__db = self.__client["NOSTYLIST"]

    # Return the database
    def getdb(self):
        return self.__db


# Instantiate the MongoDB class
mongoDB = MongoDB

# Get access to the database - use mongo_connection.db to access the db when importing this file
db = mongoDB.getdb
