from pymongo import MongoClient

# Do not edit this file


# Connect to MongoDB Atlas
connection_string = "mongodb+srv://alejandrovelez:Eggface1@cluster0.snymu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a client and connect to database
client = MongoClient(connection_string)

# Access NOSTYLIST db - make sure you call the db using mongo_connection.db when importing this file
db = client["NOSTYLIST"]
